apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: myapp-cluster
    app.kubernetes.io/instance: myapp-cluster-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: myapp-cluster
spec:
  selector:
    app: myapp-cluster
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000